/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class CadFuncionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadFuncionarios
     */
    public CadFuncionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TipoFun = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CadastrarFUN = new javax.swing.JButton();
        ALTERAR = new javax.swing.JButton();
        NomeFun = new javax.swing.JTextField();
        ExcluirFun = new javax.swing.JButton();
        MatriculaFun = new javax.swing.JTextField();
        MOSTRAR = new javax.swing.JButton();
        TipoFunText = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);

        jLabel1.setText("MATRÍCULA:");

        TipoFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "RH", "JURIDICO" }));

        jLabel2.setText("TIPO:");

        jLabel3.setText("NOME:");

        jLabel4.setText("CADASTRO DE FUNCIONÁRIO");

        CadastrarFUN.setText("CADASTRAR");
        CadastrarFUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFUNActionPerformed(evt);
            }
        });

        ALTERAR.setText("ALTERAR");
        ALTERAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTERARActionPerformed(evt);
            }
        });

        ExcluirFun.setText("EXCLUIR");
        ExcluirFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirFunActionPerformed(evt);
            }
        });

        MOSTRAR.setText("Mostrar");
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(MOSTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(ALTERAR, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(ExcluirFun))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MatriculaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TipoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TipoFunText, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(CadastrarFUN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 430, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MatriculaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(TipoFunText))
                .addGap(10, 10, 10)
                .addComponent(TipoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastrarFUN)
                    .addComponent(ExcluirFun)
                    .addComponent(ALTERAR)
                    .addComponent(MOSTRAR))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarFUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFUNActionPerformed
         String DRIVER = "com.mysql.cj.jdbc.Driver";
        String URL = "jdbc:mysql://localhost:3306/sistema_chamados?useTimezone=true&serverTimezone=UTC";
        String USER = "root";
        String PASS = "";

        try {
            Class.forName(DRIVER);
            Connection con;
            con = DriverManager.getConnection(URL, USER, PASS);

            String query; 
            query = "INSERT INTO funcionario (nome_funcionario,matricula,tipo) VALUES (?,?,?);";

            PreparedStatement stnt;
            stnt = con.prepareStatement(query);

            stnt.setString(1,NomeFun.getText()) ;
            stnt.setString(2,MatriculaFun.getText());
            stnt.setString(3,(String) TipoFun.getSelectedItem());
            stnt.executeUpdate();

           
            stnt.close();
           
            con.close();

        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possível encontrar a classe");
        } catch (SQLException e) {
            System.out.println("Erro na conexão" + e);
        }
    }//GEN-LAST:event_CadastrarFUNActionPerformed

    private void ExcluirFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirFunActionPerformed
        try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistema_chamados?useTimezone=true&serverTimezone=UTC", "root", "");

            String query = "DELETE FROM funcionario WHERE matricula = '" + MatriculaFun.getText() + "';";

            PreparedStatement stnt = con.prepareStatement(query);

            stnt.executeUpdate();
            stnt.close();
            con.close();

        } catch (SQLException e) {
            System.out.println("Erro no SQL" + e);
        }
    }//GEN-LAST:event_ExcluirFunActionPerformed

    private void ALTERARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTERARActionPerformed
         try {
            Connection con;
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistema_chamados?useTimezone=true&serverTimezone=UTC", "root", "");

            String query = "UPDATE funcionario SET nome_funcionario = ?,tipo = ? WHERE matricula = '" + MatriculaFun.getText() + "';";

            PreparedStatement stnt = con.prepareStatement(query);

            //stnt.setString(1, MatriculaFun.getText());
            stnt.setString(1, NomeFun.getText());
           stnt.setString(2, (String) TipoFun.getSelectedItem());
            
            stnt.executeUpdate();
            stnt.close();
            con.close();

        } catch (SQLException e) {
            System.out.println("Erro no SQL" + e);
        }
    }//GEN-LAST:event_ALTERARActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
       try {
           // listaSetor.removeAllItems();
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con;

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistema_chamados?useTimezone=true&serverTimezone=UTC", "root", "");

            String query = "SELECT nome_funcionario,tipo FROM funcionario WHERE matricula = (?) ;";
            
            

            PreparedStatement stnt = con.prepareStatement(query);
            
              stnt.setString(1,MatriculaFun.getText()) ;
              
            ResultSet rs;
            rs = stnt.executeQuery();

            while (rs.next()) {
               NomeFun.setText(rs.getString("nome_funcionario"));
                TipoFunText.setText(rs.getString("tipo"));
            }

        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possível encontrar a classe");
        } catch (SQLException e) {
            System.out.println("Erro no SQL" + e);
        }
    }//GEN-LAST:event_MOSTRARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALTERAR;
    private javax.swing.JButton CadastrarFUN;
    private javax.swing.JButton ExcluirFun;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JTextField MatriculaFun;
    private javax.swing.JTextField NomeFun;
    private javax.swing.JComboBox<String> TipoFun;
    private javax.swing.JTextField TipoFunText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
